language: python
python:
  - "3.7" # dataclasses needs py3.7

install:
  - pip install -r requirements.txt
  - pip install pytest coverage
  - python stexs-py/setup.py install

script:
  - export COVERAGE_RCFILE=stexs-py/stexs/tests/.coveragerc
  - coverage run --source='stexs-py/' -m pytest stexs-py/stexs/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
