anguage: python
python:
  - "3.7" # dataclasses needs py3.7

install:
  - pip install pytest sqlalchemy coverage
  - python stexs-py/setup.py install

script:
  - coverage run --source='stexs-py/' -m pytest stexs-py/stexs/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
